sudo: required
services:
    - docker

before_install:
    - docker build -t rohit/react -f Dockerfile.dev .

script:
    - docker run -e CI=true rohit/react npm run test

deploy:
    provider: azure_web_apps
    username: $AZURE_WA_USERNAME       # If AZURE_WA_USERNAME isn't set
    password: $AZURE_WA_PASSWORD   # If AZURE_WA_PASSWORD isn't set
    site: react-docker       # If AZURE_WA_SITE isn't set
    verbose: true
    #   slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
# deploy:
#     edge: true
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "react"
#     env: "React-env"
#     bucket_name: "elasticbeanstalk-us-east-2-975314484390"
#     bucket_path: "react"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
